when@dev:
    web_profiler:
        toolbar: true
        intercept_redirects: false

    framework:
        profiler:
            collect_serializer_data: true
            enabled: true
            only_exceptions: false



when@test:
    framework:
        profiler:
            collect: false
            collect_serializer_data: true
