
services:
###> doctrine/doctrine-bundle ###
  db:
    image: mysql:${MYSQL_VERSION:-8.0.36}
    container_name: symfony_voyageurmigrant-db-1
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-MYSQL_DATABASE}
      # You should definitely change the password in production
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER:-MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-MYSQL_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - db_data:/var/lib/mysql:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/mysql:rw
    networks:
      - voyageurmigrant

###< doctrine/doctrine-bundle ###
  web:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: symfony_web
    environment:
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      TRUSTED_HOSTS: ${TRUSTED_HOSTS}
      TRUSTED_PROXIES: ${TRUSTED_PROXIES}
    volumes:
      - ./:/var/www/html:cached
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - voyageurmigrant


  phpmyadmin:
    image: phpmyadmin:latest
    container_name: symfony_phpmyadmin
    restart: always
    ports:
      - "8086:80"
    environment:
      PMA_HOST: db
      PMA_USER: ${MYSQL_USER:-MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD:-MYSQL_PASSWORD}
      PMA_ARBITRARY: 1
    depends_on:
      - db
    networks:
      - voyageurmigrant

volumes:
###> doctrine/doctrine-bundle ###
  db_data:
###< doctrine/doctrine-bundle ###
networks:
  voyageurmigrant:
    driver: bridge
