networks:
  voyageurmigrant:

volumes:
  db_data:
    driver: local

services:
  web:
    build:
      context: .
      dockerfile: ./Docker/php/Dockerfile
    container_name: symfony_web
    restart: unless-stopped
    ports:
      - "8000:80"
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html:cached #optimisation des volumes
      - /var/www/html/vendor
    environment:
      APP_ENV: dev
      DATABASE_URL: mysql://root:${MYSQL_ROOT_PASSWORD}@db:3306/${MYSQL_DATABASE}
    depends_on:
      - db


  db:
    image: mysql:8.0
    container_name: symfony_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql


  phpmyadmin:
    image: phpmyadmin:latest
    container_name: symfony_phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8086:80"

